services:
  balancer:
    image: nginx:1.27.2-alpine3.20
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./nginx:/etc/nginx/templates
    depends_on:
      - rpc-gateway
      - static-gateway

  rpc-gateway:
    build:
      dockerfile: docker/rpc/Dockerfile
      context: .
    command: ["uvicorn", "rpc_gateway:app", "--host", "0.0.0.0", "--port", "8000"]
    environment:
      SERVICE_NAME: rpc_gateway_service
    ports:
      - "8001:8000"
    depends_on:
      - to-square
      - to-sqrt

  static-gateway:
    image: nginx:latest
    ports:
      - "8002:80"
    volumes:
      - ./static:/usr/share/nginx/html/static

  to-square:
    build:
      dockerfile: docker/services/Dockerfile
      context: .
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    environment:
      SERVICE_NAME: to_square_service
      DO_JOB: to_square
    ports:
      - "8003:8000"

  to-sqrt:
    build:
      dockerfile: docker/services/Dockerfile
      context: .
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    environment:
      SERVICE_NAME: to_sqrt_service
      DO_JOB: to_sqrt
    ports:
      - "8004:8000"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
